### ISSUE TITLE
fail complile in compile.exe and in sourcemod.net/compiler.php

### ISSUE THREAD

**Issue by Poiob** [Kaseaa/CSGO-spec-key#1]
could u give a .smx?thx bro

**Comment by Kasea** [comment]
dude, this is 3 years old. it was written for sourcemod 1.7 or something like that.
I don't have any intention of updating the mod, I doubt you'd need to change anything major, so if you have some experience in programming you should be able to figure it out.

Even if I gave you a .smx I doubt it would run on modern SourceMod
